# ServerProperties
server:
  port: 4001
  servlet:
    context-path: /api

# logger logback-spring.xml中配置了
#logging:
#  level.com.swking: debug
#  file:
#    path: E:\CodeSpace\JavaSpace\blog_community_server\log
#    name: blog_community.log

spring:
  # ThymeleafProperties
  thymeleaf:
    cache: false
  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: swking0917
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # MailProperties
  mail:
    host: smtp.qq.com
    port: 465
    username: swkings@qq.com
    password: erupjzdoswtfjjaa
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # RedisProperties
  redis:
    # 可以自己选择
    database: 0
    host: localhost
    port: 6379
  # KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: swking-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
      properties:
        security:
          protocol: PLAINTEXT
  # ElasticsearchProperties 7.x
  # elasticsearch:
  #   rest:
  #     uris: http://localhost:9200
  # ElasticsearchProperties 6.x
  data:
    elasticsearch:
      cluster-name: swking
      cluster-nodes: 127.0.0.1:9300
  security:
    user:
      name: swking
      password: root
  # TaskExecutionProperties
  task:
    execution:
      pool:
        # 线程池中核心线程数量
        core-size: 5
        # 线程池不够用时，线程最大数量
        max-size: 15
        # 队列长度，线程多时缓冲
        queue-capacity: 100
    # TaskSchedulingProperties
    scheduling:
      pool:
        size: 5

# MybatisProperties
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.swking.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# 自定义参数
blogCommunity:
  path:
    domain: http://localhost:8080
    upload: E:/CodeSpace/JavaSpace/blog_community_server/ext/upload
    tsp-file: E:/CodeSpace/JavaSpace/blog_community_server/ext/tsp-solver
  client:
    domain: http://localhost:3001
  enable-redis: true
  elasticsearch:
    url: 127.0.0.1:9200